### ISSUE TITLE
Perhaps make this a template from the GitHub repo settings?

### ISSUE THREAD

**Issue by chaosprint** [DGriffin91/egui_baseview_test_vst2#4]

**Comment by DGriffin91** [comment]
Nice idea. I checked the box `Template repository`. Let me know if anything else needs to change. I haven't made a template before.

**Comment by chaosprint** [comment]
> Nice idea. I checked the box `Template repository`. Let me know if anything else needs to change. I haven't made a template before.

Great! I think the rest is just for the users to change different places to their own needs such as the plugin name, etc.
